include: "rules/common.smk"

## rule targets ##

rule all:
  input:
    targets

rule all_pkg:
  input:
    pkg_tar,
    pkg_tmp
  run:
    pkg_tmp.unlink()

## rule init ##

rule pkg:
  input:
    pkg_tmp
  output:
    pkg_tar
  conda:
    "envs/R.yml"
  shell:
    "./workflow/scripts/pkg.R > {output[0]:q}"

rule reference:
  input:
    config["ref"]
  output:
    root / f"ref-{mode}.fna"
  run:
    copy2(input[0], output[0])

## rule modules ##

include: "rules/gene.smk"
include: "rules/genome.smk"
include: "rules/meta.smk"
include: "rules/phylo.smk"
