---
params:
  root: "../exp/fib"
  meta: "../data/10508.tsv"
  db: "../data/blast/10508/10508"
  entry: "FJ643676"
  range: "30775-31752"
  pidn: 90
---

```{r setup, include=F}
library(tidyverse)
source("../R/mutt.R")
knitr::opts_chunk$set(echo = F)
do.call(Sys.setenv, params)
```

Local Alignment

```{bash local}
mkdir -p "$root"
blastdbcmd -db "$db" -entry "$entry" -range "$range" > "$root/qry.fna"
blastn \
  -task blastn -num_threads 8 -max_target_seqs 20000 \
  -db "$db" -query "$root/qry.fna" -outfmt 7 > "$root/blast.tsv"
```

Global/Local Alignment

```{bash glocal}
awk '/^[^#]/ { print $2; }' "$root/blast.tsv" | uniq > "$root/acc.txt"
blastdbcmd -db "$db" -entry_batch "$root/acc.txt" > "$root/lib.fna"
time glsearch36 -m 8CB -T 8 "$root/qry.fna" "$root/lib.fna" > "$root/glsearch.tsv"
```

Extract

```{r extract-1}
df.meta <- read_tsv(params$meta, col_types = cols(.default = "c")) %>% select(accver, taxid, collection_date)

df.glsearch <-
  file.path(params$root, "glsearch.tsv") %>% 
  read_lines() %>% 
  parse_outfmt7() %>%
  filter(`% identity` >= params$pidn) %>%
  merge(df.meta, by.x = "subject id", by.y = "accver", all.x = T) %>%
  filter(!is.na(collection_date))

arrange(df.glsearch, collection_date) %>% 
  with(str_c(`subject id`, ":", `s. start`, "-", `s. end`)) %>%
  write_lines(file.path(params$root, "reg.txt"))

with(df.glsearch, 
  str_c(
    "/^>/ s/", 
    `subject id`, ":", `s. start`, "-", `s. end`, "/", 
    `subject id`, ":", `s. start`, "-", `s. end`, "|", collection_date, "|", taxid, "/"
  )
) %>% write_lines(file.path(params$root, "reg.sed"))
```

```{bash extract-2}
rm -f "$root/lib.fna.fai"
samtools faidx "$root/lib.fna" -r "$root/reg.txt" | sed -E -f "$root/reg.sed" > "$root/reg.fna"
```

Multiple Alignment

```{bash multiple-alignment}
time mafft --auto --adjustdirection --thread -1 "$root/reg.fna" > "$root/msa.fna" 2> "$root/msa.log"
```

```{r, fig.height=8, fig.width=10}
msa <- 
  file.path(params$root, "msa.fna") %>%
  ape::read.dna(format = "fasta", as.character = T) %>% 
  toupper()
msa <- msa[2:nrow(msa), ]
df.snp <- call_snp(msa)
df.ind <- call_ind(msa)
ggplot() +
  geom_point(data = df.snp, aes(pos, id, shape = call, color = call), size = 8) +
  geom_point(data = df.ind, aes(pos, id, shape = call), size = 4, position = position_nudge(y = 0.25)) +
  scale_shape_manual(values = setNames(
    c(124, 124, 124, 124, 6, 2), 
    c("trs", "trv", "sim", "dis", "ins", "del")
  )) +
  xlim(1, ncol(msa)) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```

Maximum Likelihood Tree

```{bash maximum-likelihood}
rm -f "$root/phy."*
time iqtree -s "$root/msa.fna" -pre "$root/phy" -alrt 1000 -bb 1000 -bnni -nt AUTO > /dev/null
```
