---
title: "report"
output: html_document
params:
  root: ../out
---

```{r setup, include=FALSE}
library(ggtree)
library(tidyverse)
library(tracerer)
library(parallel)
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores = detectCores())
```

```{r}
path_to_meta <- function(df)
{
  mutate_at(df, "path", str_remove, str_c("^", params$root, .Platform$file.sep, "?")) %>%
    separate(path, c("acc", "beast", "name"), .Platform$file.sep) %>%
    separate(name, c("clock", "coalescent"), "[-.]", extra = "drop") %>%
    select(-beast)
}

parse_mle_report <- function(path)
{
  lines <- read_lines(path)
  PS = "log marginal likelihood (using path sampling) from pathLikelihood.delta = "
  SS = "log marginal likelihood (using stepping stone sampling) from pathLikelihood.delta = "
  list(
    path = path,
    PS = as.double(str_sub(lines[startsWith(lines, PS)], nchar(PS) + 1)),
    SS = as.double(str_sub(lines[startsWith(lines, SS)], nchar(SS) + 1))
  )
}

df.mle <-
  list.files(params$root, pattern = ".mle.result.log", recursive = T, full.names = T) %>%
  lapply(parse_mle_report) %>%
  bind_rows() %>%
  path_to_meta() %>%
  group_by(acc) %>%
	mutate(
		`BF (PS)` = PS - PS[which(clock == "str" & coalescent == "con")],
		`BF (SS)` = SS - SS[which(clock == "str" & coalescent == "con")]
	) %>%
  ungroup() %>%
  arrange(acc, desc(`BF (PS)`))
```

```{r}
pburn <- 0.1
df.ess <-
  list.files(params$root, pattern = "\\w+-\\w+.log", recursive = T, full.names = T) %>%
  grep("(msa|run)-(1|2).log$", ., invert = T, value = T) %>%
  mclapply(function(path) {
    df <- parse_beast_log(path)
    interval <- df$state[2] - df$state[1]
    select(df, joint, prior, likelihood, age.root., meanRate, coalescent) %>%
      apply(2, function(ele) calc_ess(remove_burn_in(ele, pburn), interval)) %>%
      c(path = path)
  }) %>% 
  map_df(bind_rows) %>%
  path_to_meta() %>%
  select(acc, clock, coalescent, everything())
```

```{r}
df <- merge(df.mle, df.ess, by = c("acc", "clock", "coalescent"), sort = F)
df.top <- group_by(df, acc) %>% top_n(1, `BF (PS)`)
df
```

```{r, fig.width=10, fig.height=4}
tree <- treeio::read.beast(file.path(params$root, "ACU57010", "beast", "rln-con.mcc.tree"))
tip.date <- str_extract(tree@phylo$tip.label, "\\d{4}-\\d{2}-\\d{2}")
mrsd <- min(tip.date)
ggtree(tree, mrsd = mrsd, right = T) +
  geom_tiplab(linesize = 0.25, align = T) +
  geom_range(range = "height_0.95_HPD", color = "blue", alpha = 0.5, size = 1) +
  theme_tree2() +
  theme(
    panel.grid.major.x = element_line(color="black", size = .25),
    panel.grid.minor.x = element_line(color="grey", size = .25)
  )
```
