$schema: "http://json-schema.org/draft-06/schema#"

description: parameters

properties:
  ref:
    type: string
    description: the reference sequence query FASTA file
  bdb:
    type: string
    description: the BLAST database name
  mode:
    type: boolean
    description: the flag to set processing mode (true = genome, false = gene)
    default: False
  pkg:
    type: boolean
    description: the flag to install R packages that aren't available on conda
    default: False
  out:
    type: string
    description: the ouput directory
    default: out
  gapf:
    type: integer
    description: the number of allowable gaps flanking global/local alignment results
    default: 25
  plen:
    type: number
    description: the percentage range of the reference genome length to use for subsetting in [0, 100]
    default: 5
  blast:
    type: array
    description: the blast parameters
    default:
      - task=blastn
      - perc_identity=90
      - qcov_hsp_perc=90
      - max_target_seqs=20000
  taxidlist:
    type: string
    description: the file to restrict search of database to include only the specified taxonomy IDs on each line
  qcov_idn_perc:
    type: number
    description: the percent query coverage identity [0, 100]
    default: 90
  email:
    type: string
    description: the e-mail to identify yourself to NCBI (for politeness reasons)
    default: ""
  edb:
    type: string
    description: the NCBI database
    default: nuccore
  post_size:
    type: integer
    description: the number of records to post at a time
    default: 500
  formats:
    type: array
    description: the order of date formats to try and parse
    default:
      - "%d-%b-%Y"
      - "%Y-%m-%d"
      - "%b-%Y"
      - "%Y"
  reco_iter:
    type: integer
    description: the maximum number of iterations for gubbins
    default: 1000
  mcmc_iter:
    type: integer
    description: the number of MCMC iterations to perform for bactdating
    default: 1000000
  mcmc_thin:
    type: integer
    description: the thining interval between recorded MCMC samples for bactdating
    default: 10
  mcmc_len:
    type: integer
    description: the chain length for MCMC for BEAST
    default: 10000000
  mcmc_echo:
    type: integer
    description: the sampling frequency for MCMC for BEAST
    default: 10000
  psss_len:
    type: integer
    description: the chain length for PS/SS for BEAST
    default: 1000000
  psss_echo:
    type: integer
    description: the sampling frequency for PS/SS for BEAST
    default: 1000
  path_steps:
    type: integer
    description: the number of path steps for PS/SS for BEAST
    default: 100
