$schema: "http://json-schema.org/draft-06/schema#"

description: parameters

properties:
  qry:
    type: string
    description: the query FASTA file
  db:
    type: string
    description: the BLAST database name
  mode:
    type: boolean
    description: the flag to set processing mode (true = genome, false = gene)
    default: False
  pkg:
    type: boolean
    description: the flag to install R packages that aren't available on conda
    default: False
  out:
    type: string
    description: the ouput directory
    default: out
  cpu:
    type: integer
    description: the number of CPUs to use
    default: 8
  plen:
    type: number
    description: the percentage range of the reference genome length to use for subsetting in [0, 100]
    default: 5
  blast:
    type: array
    description: the blast parameters
    default:
      - task=blastn
      - perc_identity=90
      - qcov_hsp_perc=90
      - max_target_seqs=20000
  qcov_idn_perc:
    type: number
    description: the percent query coverage identity [0, 100]
    default: 90
  email:
    type: string
    description: the e-mail to identify yourself to NCBI (for politeness reasons)
    default: ""
  edb:
    type: string
    description: the NCBI database
    default: nuccore
  post_size:
    type: integer
    description: the number of records to post at a time
    default: 500
  formats:
    type: array
    description: the order of date formats to try and parse
    default:
      - "%d-%b-%Y"
      - "%Y-%m-%d"
      - "%b-%Y"
      - "%Y"
  iter:
    type: integer
    description: the number of MCMC iterations to perform
    default: 1000000
  thin:
    type: integer
    description: the thining interval between recorded MCMC samples
    default: 10
